# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
GMAIL_USERNAME: 
GMAIL_PASSWORD: 
#MAILCHIMP_API_KEY: Your_MailChimp_API_Key
#MAILCHIMP_LIST_ID: Your_List_ID


DOMAIN_NAME: 

TWITTER_KEY: 
TWITTER_SECRET: 

FACEBOOK_KEY: 
FACEBOOK_SECRET: 
